# Generated by Django 2.1.2 on 2018-12-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181216_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_Ch_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_Eng_name',
        ),
    ]
