# Generated by Django 2.1.2 on 2018-12-16 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20181216_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='fmvp',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_fmvp', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='season',
            name='mip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_mip', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='season',
            name='mvp',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_mvp', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='season',
            name='roy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_roy', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='season',
            name='smoy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_smoy', to='game.Player'),
        ),
    ]
