# Generated by Django 2.1.2 on 2018-12-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181216_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='imgPath',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='球队图标路径'),
        ),
        migrations.AlterField(
            model_name='team',
            name='arena',
            field=models.CharField(default='球馆', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.CharField(default='经理', max_length=20),
        ),
    ]
