# Generated by Django 2.1.2 on 2018-12-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181217_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='west_east',
            field=models.BooleanField(blank=True, default=True, verbose_name='东西部'),
        ),
    ]
